/*
    tg
    Copyright (C) 2015 Marcello Mamino

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 2 as
    published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

#include "report.h"
#include "stats.h"
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <cairo.h>
#include <cairo-pdf.h>

int report_summary(struct report_row *rows, int max_rows)
{
	int n = 0;
	struct stats_summary s;
	/* Ciclos sin posición etiquetada. */
	if(stats_summary_untagged(0, &s) > 0 && n < max_rows) {
		rows[n].position = POSITION_NONE;
		rows[n].n = s.n;
		rows[n].mean = s.mean;
		rows[n].sigma = s.sigma;
		rows[n].min = s.min;
		rows[n].max = s.max;
		rows[n].mean_be = s.mean_be;
		rows[n].mean_amp = s.mean_amp;
		n++;
	}
	/* Posiciones etiquetadas. */
	int pos;
	for(pos = 1; pos <= POSITION_CR && n < max_rows; pos++) {
		if(stats_summary_pos(pos, 0, &s) <= 0) continue;
		rows[n].position = pos;
		rows[n].n = s.n;
		rows[n].mean = s.mean;
		rows[n].sigma = s.sigma;
		rows[n].min = s.min;
		rows[n].max = s.max;
		rows[n].mean_be = s.mean_be;
		rows[n].mean_amp = s.mean_amp;
		n++;
	}
	/* Total (todas las posiciones). */
	if(n > 0 && n < max_rows && stats_summary(0, &s) > 0) {
		rows[n].position = -1;
		rows[n].n = s.n;
		rows[n].mean = s.mean;
		rows[n].sigma = s.sigma;
		rows[n].min = s.min;
		rows[n].max = s.max;
		rows[n].mean_be = s.mean_be;
		rows[n].mean_amp = s.mean_amp;
		n++;
	}
	return n;
}

static const char *row_name(int position)
{
	return position < 0 ? "total" : position_name(position);
}

int report_write_csv(const char *path, const struct report_row *rows, int n)
{
	FILE *f = fopen(path, "w");
	if(!f) return 1;
	fprintf(f, "position,n,mean,sigma,min,max,mean_be,mean_amp\n");
	if(n == 0) {
		fprintf(f, "no data\n");
		return fclose(f) ? 1 : 0;
	}
	int i;
	for(i = 0; i < n; i++) {
		fprintf(f, "%s,%d,%.3f,%.3f,%.3f,%.3f,%.3f,%.1f\n",
			row_name(rows[i].position), rows[i].n,
			rows[i].mean, rows[i].sigma, rows[i].min, rows[i].max,
			rows[i].mean_be, rows[i].mean_amp);
	}
	return fclose(f) ? 1 : 0;
}

static void pdf_text(cairo_t *cr, double x, double y, const char *s)
{
	cairo_move_to(cr, x, y);
	cairo_show_text(cr, s);
}

int report_write_pdf(const char *path, const struct report_row *rows, int n)
{
	cairo_surface_t *sfc = cairo_pdf_surface_create(path, 595, 842);
	if(!sfc || cairo_surface_status(sfc) != CAIRO_STATUS_SUCCESS) {
		if(sfc) cairo_surface_destroy(sfc);
		return 1;
	}
	cairo_t *cr = cairo_create(sfc);

	if(n == 0) {
		cairo_select_font_face(cr, "sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
		cairo_set_font_size(cr, 12);
		pdf_text(cr, 40, 120, "No measurements");
	} else {

	cairo_set_source_rgb(cr, 0, 0, 0);
	cairo_select_font_face(cr, "sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD);
	cairo_set_font_size(cr, 18);
	pdf_text(cr, 40, 60, "Tg timing report");
	cairo_select_font_face(cr, "sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
	cairo_set_font_size(cr, 10);

	double cols[] = { 40, 130, 170, 220, 270, 320, 380, 430 };
	const char *hdr[] = { "Position", "n", "Mean", "Sigma", "Min", "Max", "BE ms", "Amp deg" };
	double y = 90;
	int c;
	for(c = 0; c < 8; c++)
		pdf_text(cr, cols[c], y, hdr[c]);
	y += 16;
	int i;
	for(i = 0; i < n; i++) {
		char buf[64];
		pdf_text(cr, cols[0], y, row_name(rows[i].position));
		snprintf(buf, sizeof(buf), "%d", rows[i].n);
		pdf_text(cr, cols[1], y, buf);
		snprintf(buf, sizeof(buf), "%.3f", rows[i].mean);
		pdf_text(cr, cols[2], y, buf);
		snprintf(buf, sizeof(buf), "%.3f", rows[i].sigma);
		pdf_text(cr, cols[3], y, buf);
		snprintf(buf, sizeof(buf), "%.3f", rows[i].min);
		pdf_text(cr, cols[4], y, buf);
		snprintf(buf, sizeof(buf), "%.3f", rows[i].max);
		pdf_text(cr, cols[5], y, buf);
		snprintf(buf, sizeof(buf), "%.2f", rows[i].mean_be);
		pdf_text(cr, cols[6], y, buf);
		snprintf(buf, sizeof(buf), "%.1f", rows[i].mean_amp);
		pdf_text(cr, cols[7], y, buf);
		y += 16;
	}
	pdf_text(cr, 40, 800, "Generated by tg (https://github.com/vacaboja/tg)");
	}

	cairo_show_page(cr);
	cairo_destroy(cr);
	cairo_surface_finish(sfc);
	cairo_surface_destroy(sfc);
	return 0;
}